apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: transaction-replicaset
spec:
  selector:
    matchLabels:
      app: transaction-app
  template:
    metadata:
      labels:
        app: transaction-app
    spec:
      containers:
      - name: transaction-app
        image: transaction:0.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "localk8s"
  replicas: 1
