apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefull
spec:
  selector:
    matchLabels:
      app: db-postgres
  serviceName: db-service
  replicas: 2
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
          envFrom:
            - configMapRef:
                name: db-configmap
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: db-pvc
    
